planning_period: 0.01 # seconds
# path_offset: 2.5 # metres
max_unseen_time: 5.0 # seconds
approach_speed: 8.0 # metres per second
trajectory:
  sampling_dt: 0.2 # seconds
  horizon: 8.0 # seconds
  target_offset: 2 # metres

z_bounds:
  min: 0.0
  max: 20.0

start_position:
  [
    0.0,   # x coordinate (metres)
    -25.0,  # y coordinate (metres)
    8.0,   # z coordinate (metres)
    0.0    # yaw (radians)
  ]

observing:
  max_ball_angle: !degrees 20.0
  ball_distance: 10 # metres
  max_forward_speed: 0.1 # metres per second
