land_at_end: true

planning_period: 0.1 # seconds

# detections and predictions older than this are ignored
max_unseen_duration: 1.0 # seconds

approach_speed: 6.0 # metres per second

lurking:
  z_offset: -1.5 # metres
  reaction_dist: 15.0 # metres - when the ball gets closer than this, start reacting to its predicted trajectory
  max_reposition: 5.0 # metres
  min_observing_duration: 999.0 # the target must be observed at least this amount of seconds to start lurking
  min_last_points: 10 # how many last points at minimum to use when RANSACing the lurking position
  min_last_duration: 3 # how many last sedonds at minimum to use when RANSACing the lurking position
  passthrough_detection_distance: 4.0 # metres - when distance of the ball is smaller, the signed distnace from YZ lurk plane will be used for detecting passthrough

trajectory:
  sampling_dt: 0.2 # seconds
  horizon: 8.0 # seconds
  target_reached_distance: 666.5 # metre - at this distance from the target point it is considered to be reached
  default_speed: 3.0 # metres per second - used for boring maneuvres (such as from obs. pos. to lurk pos.)

pogo:
  min_height: 5.5 # metres
  max_height: 15.0 # metres
  speed: 1.0 # metres per second

constraint_states:
  {
    "going_to_nextpos": "ballcatch_slow",
    "waiting_for_detection": "ballcatch_slow",
    "observing": "ballcatch_slow",
    "yawing_detection": "ballcatch_slow",
    "following_detection": "ballcatch_slow",
    "following_prediction": "ballcatch_slow",
    "going_to_lurk_down": "ballcatch_slow",
    "going_to_lurk_horizontal": "ballcatch_slow",
    "going_to_lurk_up": "ballcatch_slow",
    "lurking": "ballcatch_fast",
  }

start_position:
  [
    6.0,   # x coordinate (metres)
    -8.0,  # y coordinate (metres)
    5.5,   # z coordinate (metres)
    0.0    # yaw (radians)
  ]

landing_height: 5.5 # metres
## ############### NOW SPECIFIED IN THE WORLD FILE ###############
# landing_position:
#   [
#     -30.0,   # x coordinate (metres)
#     0.0,  # y coordinate (metres)
#     5.0,   # z coordinate (metres)
#     0.0    # yaw (radians)
#   ]
