land_at_end: true

planning_period: 0.1 # seconds

# detections and predictions older than this are ignored
max_unseen_duration: 3.0 # seconds

approach_speed: 6.0 # metres per second

lurking:
  z_offset: 0.2 # metres
  reaction_dist: 8.0 # metres - when the ball gets closer than this, start reacting to its predicted trajectory
  max_reposition: 6.0 # metres
  min_observing_duration: 60.0 # the target must be observed at least this amount of seconds to start lurking
  min_last_points: 10 # how many last points at minimum to use when RANSACing the lurking position - UNUSED
  min_last_duration: 3 # how many last sedonds at minimum to use when RANSACing the lurking position - UNUSED
  passthrough_detection_distance: 10.0 # metres - when distance of the ball is smaller, the signed distnace from YZ lurk plane will be used for detecting passthrough
  land_check: true
  land_after_first_passthrough: false

trajectory:
  sampling_dt: 0.2 # seconds
  horizon: 8.0 # seconds
  target_reached_distance: 0.5 # metre - at this distance from the target point it is considered to be reached
  default_speed: 3.0 # metres per second - used for boring maneuvres (such as from obs. pos. to lurk pos.)

pogo:
  min_height: 5.5 # metres
  max_height: 15.0 # metres
  speed: 1.0 # metres per second

constraint_states:
  {
    "going_to_nextpos": "slow",
    "going_to_nextpos_low": "slow",
    "waiting_for_detection": "slow",
    "observing": "slow",
    "yawing_detection": "slow",
    "following_detection": "slow",
    "following_prediction": "slow",
    "going_to_lurk_down": "slow",
    "going_to_lurk_horizontal": "slow",
    "going_to_lurk_up": "slow",
    "lurking": "fast",
  }

start_position:
  [
    0.0,   # x coordinate (metres)
    -20.0,  # y coordinate (metres)
    10.0,   # z coordinate (metres)
    1.57    # yaw (radians)
  ]

landing_height: 5.5 # metres
## ############### NOW SPECIFIED IN THE WORLD FILE ###############
dropoff_center:
  [
    0.0,   # x coordinate (metres)
    -25.0,  # y coordinate (metres)
  ]
