planning_period: 0.01 # seconds

max_unseen_duration: 5.0 # seconds

glancing:
  yaw_rate: 1.57 # radians per second
  duration: 1.0 # seconds

approach_speed: 5.0 # metres per second
chase_speed: 5.0 # metres per second
catch_trigger_distance: 2.5 # metres

lurking:
  observe_dist: 5 # metres
  max_dist_from_trajectory: 5 # metres
  max_reposition: 0.2 # metres
  min_follow_duration: 99999999.0 # seconds
  min_points: 99999999

trajectory:
  sampling_dt: 0.2 # seconds
  horizon: 8.0 # seconds
  target_offset: 5.0 # metres

z_bounds:
  min: 3.0
  max: 20.0

constraint_ranges:
  {
    "ballcatch_fast":   3.00,
    "ballcatch_medium": 8.00,
    "ballcatch_slow":   .inf,
  }

start_position:
  [
    -30.0,   # x coordinate (metres)
    0.0,  # y coordinate (metres)
    7.5,   # z coordinate (metres)
    -0.9    # yaw (radians)
  ]
